### ISSUE TITLE
Valid match_dict errors

### ISSUE THREAD

**Issue by sam-qordoba** [Qordobacode/replaCy#26]
I have what I think is a valid match dict; the replaCy matcher says it is good. But:

```
rmatcher = ReplaceMatcher(nlp, match_dict, custom_match_hooks=custom_hooks)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sh/q/repos/service.plain.language/venv/lib/python3.6/site-packages/replacy/__init__.py", line 66, in __init__
    self._init_matcher()
  File "/Users/sh/q/repos/service.plain.language/venv/lib/python3.6/site-packages/replacy/__init__.py", line 218, in _init_matcher
    self.matcher.add(match_name, callback, patterns)
  File "matcher.pyx", line 112, in spacy.matcher.matcher.Matcher.add
  File "matcher.pyx", line 568, in spacy.matcher.matcher._preprocess_pattern
  File "matcher.pyx", line 747, in spacy.matcher.matcher._get_operators
AttributeError: 'list' object has no attribute 'items'
```

matcher._get_operators looks line:

```python
def _get_operators(spec):
    # Support 'syntactic sugar' operator '+', as combination of ONE, ZERO_PLUS
    lookup = {"*": (ZERO_PLUS,), "+": (ONE, ZERO_PLUS),
              "?": (ZERO_ONE,), "1": (ONE,), "!": (ZERO,)}
    # Fix casing
    spec = {key.upper(): values for key, values in spec.items()
            if isinstance(key, basestring)}
    if "OP" not in spec:
        return (ONE,)
    elif spec["OP"] in lookup:
        return lookup[spec["OP"]]
    else:
        keys = ", ".join(lookup.keys())
        raise KeyError(Errors.E011.format(op=spec["OP"], opts=keys))
```

the erroring line is

```python
    spec = {key.upper(): values for key, values in spec.items()
            if isinstance(key, basestring)}
```

**Comment by sam-qordoba** [comment]
It was invalid, there was one `patterns` that was still a List of Lists... so the validator could be improved...
