### ISSUE TITLE
bugs at beginning/end of sentence

### ISSUE THREAD

**Issue by sam-qordoba** [Qordobacode/replaCy#90]
`preceded_by_phrase` returns true if the match is at the beginning of the sentence (which cannot be correct)
`succeeded_by_phrase` returns true if the match is at the end of the sentence (which cannot be correct)

using version `0.49.0` of replacy

**Comment by sam-qordoba** [comment]
hmmm, sorter in confidence is throwing exceptions when the match occurs at the beginning of the string.

seems like some spaCy change (or replaCy change?) has introduced a lot of bugs

```python
>>> from service_confidence.matcher import Confidence
>>> import en_core_web_sm
>>> nlp = en_core_web_sm.load()
>>> c = Confidence(nlp)
>>> c("The way I see it, this is bad")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sh/q/repos/service.confidence/service_confidence/matcher.py", line 62, in __call__
    return self.replace_matcher(doc)
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/__init__.py", line 318, in __call__
    self.spans = component(self.spans)
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 102, in sort_suggestions
    span._.suggestions = sorted(
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 104, in <lambda>
    key=lambda x: self.score_suggestion(
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 96, in score_suggestion
    text = " ".join([doc[: span.start].text] + suggestion + [doc[span.end :].text])
  File "span.pyx", line 503, in spacy.tokens.span.Span.text.__get__
  File "span.pyx", line 190, in spacy.tokens.span.Span.__getitem__
IndexError: [E201] Span index out of range.
```

**Comment by sam-qordoba** [comment]
no matches work at start or end

```
>>> c("personally, I like this")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sh/q/repos/service.confidence/service_confidence/matcher.py", line 62, in __call__
    return self.replace_matcher(doc)
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/__init__.py", line 318, in __call__
    self.spans = component(self.spans)
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 102, in sort_suggestions
    span._.suggestions = sorted(
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 104, in <lambda>
    key=lambda x: self.score_suggestion(
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 96, in score_suggestion
    text = " ".join([doc[: span.start].text] + suggestion + [doc[span.end :].text])
  File "span.pyx", line 503, in spacy.tokens.span.Span.text.__get__
  File "span.pyx", line 190, in spacy.tokens.span.Span.__getitem__
IndexError: [E201] Span index out of range.
>>> c("this is offenseive personally,")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sh/q/repos/service.confidence/service_confidence/matcher.py", line 62, in __call__
    return self.replace_matcher(doc)
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/__init__.py", line 318, in __call__
    self.spans = component(self.spans)
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 102, in sort_suggestions
    span._.suggestions = sorted(
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 104, in <lambda>
    key=lambda x: self.score_suggestion(
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 96, in score_suggestion
    text = " ".join([doc[: span.start].text] + suggestion + [doc[span.end :].text])
  File "span.pyx", line 503, in spacy.tokens.span.Span.text.__get__
  File "span.pyx", line 190, in spacy.tokens.span.Span.__getitem__
IndexError: [E201] Span index out of range.
>>> c("this is offensive, personally")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sh/q/repos/service.confidence/service_confidence/matcher.py", line 62, in __call__
    return self.replace_matcher(doc)
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/__init__.py", line 318, in __call__
    self.spans = component(self.spans)
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 102, in sort_suggestions
    span._.suggestions = sorted(
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 104, in <lambda>
    key=lambda x: self.score_suggestion(
  File "/Users/sh/Library/Caches/pypoetry/virtualenvs/service.confidence-HAQAov7T-py3.8/lib/python3.8/site-packages/replacy/scorer.py", line 96, in score_suggestion
    text = " ".join([doc[: span.start].text] + suggestion + [doc[span.end :].text])
  File "span.pyx", line 503, in spacy.tokens.span.Span.text.__get__
  File "span.pyx", line 190, in spacy.tokens.span.Span.__getitem__
IndexError: [E201] Span index out of range.
>>> c("this is offensive, personally, you know")
[ personally,]
```
